name: "run HUD pipeline"

on:
  workflow_dispatch:
  schedule:
    - cron: "0 23 * * *"

jobs:
  run:
    name: Run
    runs-on: ubuntu-latest
    steps:
      - name: Checkout this repo
        uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Python dependencies
        run: pip install -r requirements.txt

      - name: Download new files
        run: make download

      - name: Convert raw files into JSONL
        run: make parse

      - name: Combine converted JSONL into output JSONL
        run: make combine

      - name: Package output into .zip
        run: make package

      - name: Configure git
        run: git config --global user.email "actions@users.noreply.github.com" && git config --global user.name "Automated"

      - name: Commit changes
        run: git add data && (git diff --cached --quiet || git commit -m "Fetch and process newly available reports")

      - name: Push changes
        run: git push
